name: Publish Docker Image
description: |
  This workflow builds a multi-arch image and pushes it to the registry.

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      registry:
        required: true
        type: string
      image-type:
        required: false
        type: string
        default: build

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

jobs:
  compose-image-name:
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.image_name.outputs.IMAGE_NAME }}
    steps:
      - name: Compose Image Name
        id: image_name
        run: |
          if [ "${{ inputs.image-type }}" == "build" ]; then
            echo "IMAGE_NAME=${{ inputs.registry }}/${{ github.repository_owner }}/key4hep-images/${{ inputs.os }}" >> $GITHUB_OUTPUT
          else
            echo "IMAGE_NAME=${{ inputs.registry }}/${{ github.repository_owner }}/key4hep-images/${{ inputs.os }}-${{ inputs.image-type }}" >> $GITHUB_OUTPUT
          fi

  build-linux-amd64:
    needs: compose-image-name
    uses: ./.github/workflows/docker-build-push-template.yaml
    with:
      os: ${{ inputs.os }}
      runner: ubuntu-latest
      platform: amd64
      registry: ${{ inputs.registry }}
      image-type: ${{ inputs.image-type }}
      image-name: ${{ needs.compose-image-name.outputs.image-name }}
  
  build-linux-arm64:
    needs: compose-image-name
    uses: ./.github/workflows/docker-build-push-template.yaml
    with:
      os: ${{ inputs.os }}
      runner: ubuntu-24.04-arm
      platform: arm64
      registry: ${{ inputs.registry }}
      image-type: ${{ inputs.image-type }}
      image-name: ${{ needs.compose-image-name.outputs.image-name }}

  publish-multiarch:
    needs:
      - build-linux-amd64
      - build-linux-arm64
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.compose-image-name.outputs.image-name }}
          flavor: latest=${{ github.ref == 'refs/heads/main' }}
      - name: Change string case for amd64
        id: lowercase-amd64
        uses: Entepotenz/change-string-case-action-min-dependencies@v1
        with:
          string: ${{ needs.build-linux-amd64.outputs.image-uri }}
      - name: Change string case for arm64
        id: lowercase-arm64
        uses: Entepotenz/change-string-case-action-min-dependencies@v1
        with:
          string: ${{ needs.build-linux-arm64.outputs.image-uri }}
      - name: Create manifest
        id: build
        uses: int128/docker-manifest-create-action@v2
        with:
          index-annotations: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          sources: |
            ${{ steps.lowercase-amd64.outputs.lowercase }}
            ${{ steps.lowercase-arm64.outputs.lowercase }}
